#!/bin/bash

set -o errexit
set -o pipefail
set -o nounset


python /project/manage.py collectstatic --noinput

exec /usr/local/bin/gunicorn config.asgi --bind 0.0.0.0:5000 --chdir=/project -k uvicorn_worker.UvicornWorker
